"""Pure NostalgiaBox domain types and timeline rules."""

from nostalgiabox.domain.catalogue import (
    CatalogueDomainError,
    CatalogueItem,
    CatalogueItemId,
    InvalidMediaFileError,
    InvalidPlayableRenditionError,
    MediaFile,
    MediaFileId,
    MediaSource,
    MediaSourceId,
    MediaSourceKind,
    PlayableRendition,
    PlayableRenditionId,
    PreferredRenditionConflictError,
    RenditionOverlapError,
    validate_physical_duration,
    validate_rendition_set,
)
from nostalgiabox.domain.clock import Clock, SystemClock
from nostalgiabox.domain.exceptions import (
    EmptyTimelineError,
    InvalidChannelError,
    InvalidIdentifierError,
    InvalidMediaItemError,
    InvalidTimelineEntryError,
    NaiveDateTimeError,
    TimelineChannelMismatchError,
    TimelineGapError,
    TimelineNotCoveredError,
    TimelineOrderError,
    TimelineOverlapError,
)
from nostalgiabox.domain.models import (
    Channel,
    ChannelId,
    ContentKind,
    MediaItem,
    MediaItemId,
    TimelineEntry,
    TimelineEntryId,
)
from nostalgiabox.domain.timeline import (
    ChannelTimeline,
    ResolvedTimelineEntry,
    build_sequential_timeline,
    resolve_active_entry,
)

__all__ = [
    "CatalogueDomainError",
    "CatalogueItem",
    "CatalogueItemId",
    "Channel",
    "ChannelId",
    "ChannelTimeline",
    "Clock",
    "ContentKind",
    "EmptyTimelineError",
    "InvalidChannelError",
    "InvalidIdentifierError",
    "InvalidMediaFileError",
    "InvalidMediaItemError",
    "InvalidPlayableRenditionError",
    "InvalidTimelineEntryError",
    "MediaFile",
    "MediaFileId",
    "MediaItem",
    "MediaItemId",
    "MediaSource",
    "MediaSourceId",
    "MediaSourceKind",
    "NaiveDateTimeError",
    "PlayableRendition",
    "PlayableRenditionId",
    "PreferredRenditionConflictError",
    "RenditionOverlapError",
    "ResolvedTimelineEntry",
    "SystemClock",
    "TimelineChannelMismatchError",
    "TimelineEntry",
    "TimelineEntryId",
    "TimelineGapError",
    "TimelineNotCoveredError",
    "TimelineOrderError",
    "TimelineOverlapError",
    "build_sequential_timeline",
    "resolve_active_entry",
    "validate_physical_duration",
    "validate_rendition_set",
]
